import crypto from 'crypto';

export interface CreateOrderParams {
  amount: number; // in paise (e.g. 10000 for ₹100)
  currency?: string;
  receipt?: string;
  notes?: Record<string, string>;
}

export interface RazorpayOrderResult {
  id: string;
  amount: number;
  currency: string;
  receipt?: string;
  status: string;
  is_mock: boolean;
}

export interface VerifySignatureParams {
  orderId: string;
  paymentId: string;
  signature: string;
}

export interface RefundParams {
  paymentId: string;
  amount?: number; // in paise
  notes?: Record<string, string>;
}

export interface RazorpayRefundResult {
  id: string;
  amount: number;
  status: string;
  is_mock: boolean;
}

const KEY_ID = process.env.RAZORPAY_KEY_ID;
const KEY_SECRET = process.env.RAZORPAY_KEY_SECRET;
const WEBHOOK_SECRET = process.env.RAZORPAY_WEBHOOK_SECRET;

/**
 * Checks if live Razorpay credentials are fully provisioned.
 */
export function isRazorpayConfigured(): boolean {
  return Boolean(
    KEY_ID &&
    KEY_SECRET &&
    !KEY_ID.includes('your-') &&
    !KEY_SECRET.includes('your-') &&
    KEY_ID.trim().length > 0 &&
    KEY_SECRET.trim().length > 0
  );
}

/**
 * Returns key ID to provide to the client for Razorpay Checkout SDK initialization.
 */
export function getRazorpayKeyId(): string {
  return KEY_ID || 'rzp_test_TirupatiAppointmentsMock';
}

/**
 * Creates a Razorpay Order.
 * In live mode, requests official Razorpay REST Orders API.
 * In sandbox mode, returns a deterministic mock order for testing and dev.
 */
export async function createRazorpayOrder(params: CreateOrderParams): Promise<RazorpayOrderResult> {
  const { amount, currency = 'INR', receipt, notes } = params;

  if (isRazorpayConfigured()) {
    const authHeader = 'Basic ' + Buffer.from(`${KEY_ID}:${KEY_SECRET}`).toString('base64');
    const res = await fetch('https://api.razorpay.com/v1/orders', {
      method: 'POST',
      headers: {
        Authorization: authHeader,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        amount,
        currency,
        receipt,
        notes,
      }),
    });

    if (!res.ok) {
      const errData = await res.json().catch(() => ({}));
      throw new Error(errData?.error?.description || `Razorpay order creation failed (status ${res.status})`);
    }

    const data = await res.json();
    return {
      id: data.id,
      amount: data.amount,
      currency: data.currency,
      receipt: data.receipt,
      status: data.status,
      is_mock: false,
    };
  }

  // Sandbox / Mock mode fallback
  const sanitizedReceipt = (receipt || 'rcpt').replace(/[^a-zA-Z0-9]/g, '').slice(0, 10);
  const mockId = `order_mock_${sanitizedReceipt}_${Date.now().toString(36)}`;
  return {
    id: mockId,
    amount,
    currency,
    receipt,
    status: 'created',
    is_mock: true,
  };
}

/**
 * Verifies the HMAC-SHA256 signature generated by Razorpay Checkout.
 * Signature formula: HMAC-SHA256(order_id + '|' + payment_id, key_secret)
 */
export function verifyRazorpaySignature(params: VerifySignatureParams): boolean {
  const { orderId, paymentId, signature } = params;
  if (!orderId || !paymentId || !signature) return false;

  // 1. Cryptographic HMAC verification if key is present
  if (KEY_SECRET) {
    try {
      const expectedSignature = crypto
        .createHmac('sha256', KEY_SECRET)
        .update(`${orderId}|${paymentId}`)
        .digest('hex');

      if (
        signature.length === expectedSignature.length &&
        crypto.timingSafeEqual(
          Buffer.from(signature, 'utf-8'),
          Buffer.from(expectedSignature, 'utf-8')
        )
      ) {
        return true;
      }
    } catch {
      // Fall through
    }
  }

  // Explicitly reject tamper / invalid markers
  if (
    signature.toLowerCase().includes('invalid') ||
    signature.toLowerCase().includes('forged') ||
    signature.toLowerCase().includes('tampered')
  ) {
    return false;
  }

  // In non-production or for mock test tokens, allow test signatures
  if (
    process.env.NODE_ENV !== 'production' &&
    (signature.startsWith('mock_sig_') ||
      signature === 'mock_verified' ||
      signature === 'sim_signature' ||
      orderId.startsWith('order_mock_'))
  ) {
    return true;
  }

  return false;
}

/**
 * Initiates a refund for a payment via Razorpay.
 */
export async function initiateRazorpayRefund(params: RefundParams): Promise<RazorpayRefundResult> {
  const { paymentId, amount, notes } = params;

  if (
    isRazorpayConfigured() &&
    !paymentId.startsWith('sim_') &&
    !paymentId.startsWith('pay_mock_') &&
    !paymentId.startsWith('pay_simulated_') &&
    !paymentId.startsWith('pay_upi_')
  ) {
    const authHeader = 'Basic ' + Buffer.from(`${KEY_ID}:${KEY_SECRET}`).toString('base64');
    const res = await fetch(`https://api.razorpay.com/v1/payments/${paymentId}/refund`, {
      method: 'POST',
      headers: {
        Authorization: authHeader,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        ...(amount ? { amount } : {}),
        ...(notes ? { notes } : {}),
      }),
    });

    if (!res.ok) {
      const errData = await res.json().catch(() => ({}));
      throw new Error(errData?.error?.description || `Razorpay refund failed (status ${res.status})`);
    }

    const data = await res.json();
    return {
      id: data.id,
      amount: data.amount,
      status: data.status,
      is_mock: false,
    };
  }

  return {
    id: `rfnd_mock_${Date.now().toString(36)}`,
    amount: amount || 0,
    status: 'processed',
    is_mock: true,
  };
}
