import crypto from 'crypto';

export interface CreateOrderParams {
  amount: number; // in paise (e.g. 10000 for ₹100)
  currency?: string;
  receipt?: string;
  notes?: Record<string, string>;
}

export interface RazorpayOrderResult {
  id: string;
  amount: number;
  currency: string;
  receipt?: string;
  status: string;
  is_mock: boolean;
}

export interface VerifySignatureParams {
  orderId: string;
  paymentId: string;
  signature: string;
}

export interface RefundParams {
  paymentId: string;
  amount?: number; // in paise
  notes?: Record<string, string>;
}

export interface RazorpayRefundResult {
  id: string;
  amount: number;
  status: string;
  is_mock: boolean;
}

const KEY_ID = process.env.RAZORPAY_KEY_ID;
const KEY_SECRET = process.env.RAZORPAY_KEY_SECRET;
const WEBHOOK_SECRET = process.env.RAZORPAY_WEBHOOK_SECRET;

// Fail-fast production guard: Ensure critical payment secrets are configured
if (process.env.NODE_ENV === 'production') {
  if (!process.env.RAZORPAY_KEY_SECRET) {
    throw new Error('CRITICAL SECURITY CONFIGURATION ERROR: RAZORPAY_KEY_SECRET environment variable is required in production.');
  }
}

/**
 * Checks if live Razorpay credentials are fully provisioned.
 */
export function isRazorpayConfigured(): boolean {
  const keyId = process.env.RAZORPAY_KEY_ID;
  const keySecret = process.env.RAZORPAY_KEY_SECRET;
  return Boolean(
    keyId &&
    keySecret &&
    !keyId.includes('your-') &&
    !keySecret.includes('your-') &&
    keyId.trim().length > 0 &&
    keySecret.trim().length > 0
  );
}

/**
 * Returns key ID to provide to the client for Razorpay Checkout SDK initialization.
 */
export function getRazorpayKeyId(): string {
  return process.env.RAZORPAY_KEY_ID || '';
}

/**
 * Creates a Razorpay Order.
 * In live mode, requests official Razorpay REST Orders API.
 * In sandbox mode, returns a deterministic mock order for testing and dev only if mock payments are explicitly allowed.
 */
export async function createRazorpayOrder(params: CreateOrderParams): Promise<RazorpayOrderResult> {
  const { amount, currency = 'INR', receipt, notes } = params;

  // Sandbox / Mock mode — generate deterministic synthetic mock order when explicitly opted in non-production
  if (canMockPayments()) {
    const sanitizedReceipt = (receipt || 'rcpt').replace(/[^a-zA-Z0-9]/g, '').slice(0, 10);
    const mockId = `order_mock_${amount}_${sanitizedReceipt}_${Date.now().toString(36)}`;
    return {
      id: mockId,
      amount,
      currency,
      receipt: sanitizedReceipt,
      status: 'created',
      is_mock: true,
    };
  }

  if (isRazorpayConfigured()) {
    const keyId = process.env.RAZORPAY_KEY_ID!;
    const keySecret = process.env.RAZORPAY_KEY_SECRET!;
    const authHeader = 'Basic ' + Buffer.from(`${keyId}:${keySecret}`).toString('base64');
    const res = await fetch('https://api.razorpay.com/v1/orders', {
      method: 'POST',
      headers: {
        Authorization: authHeader,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        amount,
        currency,
        receipt,
        notes,
      }),
    });

    if (!res.ok) {
      const errData = await res.json().catch(() => ({}));
      throw new Error(errData?.error?.description || `Razorpay order creation failed (status ${res.status})`);
    }

    const data = await res.json();
    return {
      id: data.id,
      amount: data.amount,
      currency: data.currency,
      receipt: data.receipt,
      status: data.status,
      is_mock: false,
    };
  }

  throw new Error('Razorpay credentials are not configured and mock payments are disabled.');
}

/**
 * Checks if running in test / sandbox mode.
 */
export function isTestMode(): boolean {
  const keyId = process.env.RAZORPAY_KEY_ID;
  return !keyId || keyId.startsWith('rzp_test_') || process.env.NODE_ENV !== 'production';
}

/**
 * Determines whether mock payment bypass is permitted.
 * Strictly forbidden in production; requires explicit opt-in via ALLOW_MOCK_PAYMENTS.
 */
export function canMockPayments(): boolean {
  return process.env.ALLOW_MOCK_PAYMENTS === 'true' && process.env.NODE_ENV !== 'production';
}

/**
 * Verifies the HMAC-SHA256 signature generated by Razorpay Checkout.
 * Signature formula: HMAC-SHA256(order_id + '|' + payment_id, key_secret)
 */
export function verifyRazorpaySignature(params: VerifySignatureParams): boolean {
  const { orderId, paymentId, signature } = params;
  if (!orderId || !paymentId || !signature) return false;

  // 1. Explicitly reject tamper / invalid markers
  if (
    signature.toLowerCase().includes('invalid') ||
    signature.toLowerCase().includes('forged') ||
    signature.toLowerCase().includes('tampered')
  ) {
    return false;
  }

  // 2. Cryptographic HMAC verification strictly using RAZORPAY_KEY_SECRET
  const secret = process.env.RAZORPAY_KEY_SECRET;
  if (secret) {
    try {
      const expectedSignature = crypto
        .createHmac('sha256', secret)
        .update(`${orderId}|${paymentId}`)
        .digest('hex');

      if (
        signature.length === expectedSignature.length &&
        crypto.timingSafeEqual(
          Buffer.from(signature, 'utf-8'),
          Buffer.from(expectedSignature, 'utf-8')
        )
      ) {
        return true;
      }
    } catch {
      // Fall through
    }
  }

  // 3. Mock verification ONLY when explicitly enabled in non-production environments
  // AND the order was specifically created in mock mode (starts with order_mock_)
  if (
    canMockPayments() &&
    orderId.startsWith('order_mock_') &&
    (signature.startsWith('mock_sig_') ||
      signature === 'mock_verified' ||
      signature === 'sim_signature' ||
      signature.startsWith('test_sig_'))
  ) {
    return true;
  }

  return false;
}

export interface RazorpayPaymentDetails {
  id: string;
  status: string;
  order_id: string;
  amount: number; // in paise
  currency: string;
}

/**
 * Fetches payment details from the Razorpay API to verify status and order linkage.
 */
export async function fetchRazorpayPayment(paymentId: string): Promise<RazorpayPaymentDetails | null> {
  if (!paymentId || !paymentId.trim()) return null;

  // 1. Mock payment response ONLY if explicitly enabled AND strictly in non-production
  if (canMockPayments()) {
    // Explicit failure simulation — always return null regardless of config
    if (
      paymentId.includes('fake') ||
      paymentId.includes('invalid') ||
      paymentId.includes('unverified') ||
      paymentId.includes('tampered') ||
      paymentId.includes('nonexistent') ||
      paymentId.includes('fail')
    ) {
      return null;
    }
    // When mock payments are enabled (test/dev), any synthetic payment ID
    // (sim_, mock_, pay_) gets a captured mock response instead of hitting live Razorpay.
    if (
      paymentId.startsWith('sim_') ||
      paymentId.startsWith('mock_') ||
      paymentId.startsWith('pay_')
    ) {
      return {
        id: paymentId,
        status: 'captured',
        order_id: 'order_test_mock',
        amount: 11000,
        currency: 'INR',
      };
    }
  }

  // 2. Query live Razorpay REST API when credentials are configured
  if (isRazorpayConfigured()) {
    try {
      const keyId = process.env.RAZORPAY_KEY_ID!;
      const keySecret = process.env.RAZORPAY_KEY_SECRET!;
      const authHeader = 'Basic ' + Buffer.from(`${keyId}:${keySecret}`).toString('base64');
      const res = await fetch(`https://api.razorpay.com/v1/payments/${encodeURIComponent(paymentId)}`, {
        method: 'GET',
        headers: {
          Authorization: authHeader,
          'Content-Type': 'application/json',
        },
      });
      if (!res.ok) {
        return null;
      }
      const data = await res.json();
      return {
        id: data.id,
        status: data.status,
        order_id: data.order_id,
        amount: data.amount,
        currency: data.currency,
      };
    } catch (err) {
      console.error('[Razorpay] fetch payment failed:', err);
      return null;
    }
  }

  return null;
}

export interface RazorpayOrderDetails {
  id: string;
  amount: number; // in paise
  amount_paid?: number;
  currency: string;
  receipt?: string;
  status: string;
  notes?: Record<string, string>;
  is_mock?: boolean;
}

/**
 * Fetches order details from the Razorpay API to verify status and amount.
 */
export async function fetchRazorpayOrder(orderId: string): Promise<RazorpayOrderDetails | null> {
  if (!orderId || !orderId.trim()) return null;

  // 1. Mock order response ONLY if explicitly enabled AND the order was created in mock mode
  if (canMockPayments() && (orderId.startsWith('order_mock_') || orderId.startsWith('mock_'))) {
    if (
      orderId.includes('invalid') ||
      orderId.includes('fake') ||
      orderId.includes('nonexistent')
    ) {
      return null;
    }
    if (orderId.includes('tampered')) {
      return {
        id: orderId,
        amount: 100, // 1 INR tampered amount (mismatched with booking deposit/total)
        currency: 'INR',
        status: 'created',
        is_mock: true,
      };
    }
    const mockAmountMatch = orderId.match(/^order_mock_(\d+)_/);
    const mockAmount = mockAmountMatch ? parseInt(mockAmountMatch[1], 10) : 11000;
    return {
      id: orderId,
      amount: mockAmount,
      currency: 'INR',
      status: 'created',
      is_mock: true,
    };
  }

  // 2. Query live Razorpay REST API when credentials are configured
  if (isRazorpayConfigured()) {
    try {
      const keyId = process.env.RAZORPAY_KEY_ID!;
      const keySecret = process.env.RAZORPAY_KEY_SECRET!;
      const authHeader = 'Basic ' + Buffer.from(`${keyId}:${keySecret}`).toString('base64');
      const res = await fetch(`https://api.razorpay.com/v1/orders/${encodeURIComponent(orderId)}`, {
        method: 'GET',
        headers: {
          Authorization: authHeader,
          'Content-Type': 'application/json',
        },
      });
      if (!res.ok) {
        return null;
      }
      const data = await res.json();
      return {
        id: data.id,
        amount: data.amount,
        amount_paid: data.amount_paid,
        currency: data.currency,
        receipt: data.receipt,
        status: data.status,
        notes: data.notes,
        is_mock: false,
      };
    } catch (err) {
      console.error('[Razorpay] fetch order failed:', err);
      return null;
    }
  }

  return null;
}

/**
 * Initiates a refund for a payment via Razorpay.
 */
export async function initiateRazorpayRefund(params: RefundParams): Promise<RazorpayRefundResult> {
  const { paymentId, amount, notes } = params;

  // Simulated failure hook for test runs (strictly non-production)
  if (canMockPayments() && (paymentId.includes('fail') || paymentId.includes('error'))) {
    throw new Error('Simulated Razorpay refund gateway failure');
  }

  const isSyntheticMock =
    canMockPayments() &&
    (paymentId.startsWith('sim_') ||
      paymentId.startsWith('mock_') ||
      paymentId.startsWith('pay_'));

  if (isRazorpayConfigured() && !isSyntheticMock) {
    const keyId = process.env.RAZORPAY_KEY_ID!;
    const keySecret = process.env.RAZORPAY_KEY_SECRET!;
    const authHeader = 'Basic ' + Buffer.from(`${keyId}:${keySecret}`).toString('base64');
    const res = await fetch(`https://api.razorpay.com/v1/payments/${paymentId}/refund`, {
      method: 'POST',
      headers: {
        Authorization: authHeader,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        ...(amount ? { amount } : {}),
        ...(notes ? { notes } : {}),
      }),
    });

    if (!res.ok) {
      const errData = await res.json().catch(() => ({}));
      throw new Error(errData?.error?.description || `Razorpay refund failed (status ${res.status})`);
    }

    const data = await res.json();
    return {
      id: data.id,
      amount: data.amount,
      status: data.status,
      is_mock: false,
    };
  }

  if (canMockPayments()) {
    return {
      id: `rfnd_mock_${Date.now().toString(36)}`,
      amount: amount || 0,
      status: 'processed',
      is_mock: true,
    };
  }

  throw new Error('Razorpay credentials are not configured and mock refunds are disabled.');
}
