import { BusinessVertical, VerticalConfig } from '@appointments/shared';

export const VERTICAL_CONFIGS: Record<BusinessVertical, VerticalConfig> = {
  salons: {
    id: 'salons',
    name: 'Salons & Spas',
    badgeLabel: 'Salon Workspace',
    venueLabel: 'Salon',
    venueLabelPlural: 'Salons',
    resourceLabelSingular: 'Stylist',
    resourceLabelPlural: 'Stylists & Barbers',
    unitLabelSingular: 'Styling Chair',
    unitLabelPlural: 'Chairs & Stations',
    customerLabel: 'Client',
    actionVerb: 'Styling & Spa Session',
    departments: [
      'Hair Styling & Cut',
      'Beard & Grooming',
      'Facial & Skin Care',
      'Hair Spa & Keratin',
      'Bridal & Party Makeover',
      'Nail Art & Pedicure',
    ],
    defaultDurationMinutes: 45,
    defaultPrice: 400,
    defaultDeposit: 75,
    features: {
      hasPrescriptions: false,
      hasTokenNumbers: false,
      hasCustomDurations: true,
      hasTeamCovers: false,
    },
  },
  clinics: {
    id: 'clinics',
    name: 'Hospitals & Clinics',
    badgeLabel: 'Hospital Workspace',
    venueLabel: 'Hospital',
    venueLabelPlural: 'Hospitals',
    resourceLabelSingular: 'Doctor',
    resourceLabelPlural: 'Doctors & Specialists',
    unitLabelSingular: 'OPD Chamber',
    unitLabelPlural: 'Chambers & Beds',
    customerLabel: 'Patient',
    actionVerb: 'Medical Consultation',
    departments: [
      'General Medicine',
      'Cardiology',
      'Dental & Implantology',
      'Orthopedics & Spine',
      'Pediatrics & Neonatal',
      'Dermatology & Skin',
      'ENT & Ophthalmology',
      'General Surgery',
    ],
    defaultDurationMinutes: 30,
    defaultPrice: 500,
    defaultDeposit: 100,
    features: {
      hasPrescriptions: true,
      hasTokenNumbers: true,
      hasCustomDurations: false,
      hasTeamCovers: false,
    },
  },
  gaming: {
    id: 'gaming',
    name: 'Gaming & Turf',
    badgeLabel: 'Turf Arena',
    venueLabel: 'Turf',
    venueLabelPlural: 'Turfs',
    resourceLabelSingular: 'Arena / Court',
    resourceLabelPlural: 'Courts & Turfs',
    unitLabelSingular: 'Pitch / Station',
    unitLabelPlural: 'Pitches & Consoles',
    customerLabel: 'Team Captain / Player',
    actionVerb: 'Match / Turf Slot',
    departments: [
      'Box Cricket (7-a-side)',
      'Football Turf (5-a-side)',
      'Badminton Court A',
      'Badminton Court B',
      'PS5 & VR Arena',
    ],
    defaultDurationMinutes: 60,
    defaultPrice: 1200,
    defaultDeposit: 200,
    features: {
      hasPrescriptions: false,
      hasTokenNumbers: false,
      hasCustomDurations: true,
      hasTeamCovers: true,
    },
  },
  restaurants: {
    id: 'restaurants',
    name: 'Restaurants & Dining',
    badgeLabel: 'Dining Reservation',
    venueLabel: 'Restaurant',
    venueLabelPlural: 'Restaurants',
    resourceLabelSingular: 'Table',
    resourceLabelPlural: 'Tables & Dining Zones',
    unitLabelSingular: 'Dining Table',
    unitLabelPlural: 'Tables & Cabanas',
    customerLabel: 'Guest',
    actionVerb: 'Table Reservation',
    departments: [
      'AC Family Hall',
      'Rooftop Lounge',
      'Garden Dining',
      'Private Dining Room (PDR)',
    ],
    defaultDurationMinutes: 90,
    defaultPrice: 200,
    defaultDeposit: 100,
    features: {
      hasPrescriptions: false,
      hasTokenNumbers: false,
      hasCustomDurations: false,
      hasTeamCovers: true,
    },
  },
  pets: {
    id: 'pets',
    name: 'Pet Care & Clinic',
    badgeLabel: 'Pet Care Center',
    venueLabel: 'Pet Clinic',
    venueLabelPlural: 'Pet Clinics',
    resourceLabelSingular: 'Veterinarian / Groomer',
    resourceLabelPlural: 'Veterinarians & Groomers',
    unitLabelSingular: 'Treatment Table',
    unitLabelPlural: 'Consultation & Grooming Suites',
    customerLabel: 'Pet Parent',
    actionVerb: 'Pet Care Session',
    departments: [
      'Veterinary Checkup',
      'Vaccination Schedule',
      'Pet Spa & Grooming',
      'Dental Cleaning',
      'Surgical Consultation',
    ],
    defaultDurationMinutes: 30,
    defaultPrice: 450,
    defaultDeposit: 50,
    features: {
      hasPrescriptions: true,
      hasTokenNumbers: true,
      hasCustomDurations: false,
      hasTeamCovers: false,
    },
  },
};

export function getVerticalConfig(categoryId?: string | null): VerticalConfig {
  if (!categoryId) return VERTICAL_CONFIGS.clinics;
  const key = categoryId.toLowerCase().trim() as BusinessVertical;
  return VERTICAL_CONFIGS[key] || VERTICAL_CONFIGS.clinics;
}
